name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
    contents: write

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: gnucobol-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          curl https://github.com/OCamlPro/superbol-artefacts/releases/download/gnucobol-3.2-aio-20240624/gnucobol-3.2-aio-20240624-user.msi -L --output installer.msi &&^
          dir
          
      - name: install
        shell: cmd
        run: start /wait .\installer.msi /qn

      - name: Set LOCALAPPDATA
        id: localappdata
        shell: cmd
        run: |
          echo %LOCALAPPDATA% &&^
          echo LOCALAPPDATA="%LOCALAPPDATA:\=/%" >> %GITHUB_OUTPUT%

      - shell: cmd
        run: echo ${{ steps.localappdata.outputs.LOCALAPPDATA }}
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "${{ steps.localappdata.outputs.LOCALAPPDATA }}/GnuCOBOL"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.localappdata.outputs.LOCALAPPDATA }}/GnuCOBOL/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
